### PR TITLE
Update UI for nav

### PR DESCRIPTION
**Pull request by lukes-code**
Update UI for nav

### CODE REVIEW

**Comment by Code-Recursion** [comment]
@lukes-code thanks for PR kindly update Screen shots and explain what changes have you made if possible add a live version deployed on gh-pages to get your PR merged

**Comment by lukes-code** [comment]
Sure! I've made the navbar full width with a slight box shadow.
image

**Comment by Code-Recursion** [comment]
@lukes-code this looks weird it was better before just change little stylings in previous version don't change it

**Review by Code-Recursion — CHANGES_REQUESTED** [review]
More work needed

**Pull request closed without merging**
